# Generated by Django 4.0.4 on 2022-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_dexcom_refresh_token_user_tconnect_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_target_bg',
            field=models.FloatField(default=140),
        ),
    ]
