# Generated by Django 4.0.4 on 2022-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_current_target_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dexcom_access_token',
            field=models.TextField(null=True),
        ),
    ]
