# Generated by Django 4.0.4 on 2022-05-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_dexcom_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesentry',
            name='insulin_on_board',
        ),
    ]
