# Generated by Django 4.0.4 on 2022-05-09 06:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_diabetesentry_insulin_on_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesentry',
            name='insulin_on_board',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=list, size=None),
        ),
    ]
