# Generated by Django 4.0.4 on 2022-05-09 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_diabetesentry_insulin_on_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_fetched_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
