# Generated by Django 4.0.4 on 2022-06-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_current_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesentry',
            name='basel_delivery_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diabetesentry',
            name='basel_duration',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='diabetesentry',
            name='basel_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='diabetesentry',
            name='basel_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='diabetesentry',
            name='is_manual_bolus',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
